### PR TITLE
Multiple days

### LINKED ISSUE #13: Update minimum Elixir version to 1.7
https://elixir-lang.org/blog/2018/07/25/elixir-v1-7-0-released/

### PR DESCRIPTION
**Pull request by manuel-rubio**
And closes #13 and #14.

### CODE REVIEW

**Comment by jbernardo95** [comment]
@manuel-rubio First of all thank you so much for the contribution ! 🙌

Now going into the pr:
1. I see that the issue title is "Multiple days", but this does not tell me much, can you please elaborate on this ? Tell me what you are trying to achieve with some examples ?
2. I quickly looked at the code and saw that there are not tests, can you please add them ? Tests are a good way to explain me what you are trying to implemente here.
3. I see that you included fixes for #13 and #14 which is awesome ! But, to make sure changes are isolated from one another can you please open a new pr for each one of these changes ?

If any of this was not clear, please tell me so I can explain it better 🙂Thanks again !

**Comment by manuel-rubio** [comment]
@jbernardo95 actually I found the commits from @paweljw and I was interested mainly in the fix to run cronex every minute and not every 30 seconds.

Reading the code I guess it's letting to you to add more than one day in the configuration, but not completely sure, @paweljw could you explain or give us an example about how to use your modification?

**Comment by paweljw** [comment]
We're using it like this:

```elixir
every [:monday, :tuesday, :wednesday, :thursday, :friday], at: "06:00" do
# ...
end
```

That being said, it's a spur-of-the-moment fork and patch; the code is not documented, not covered with tests, and consists mostly of copypasta. I would not recommend merging it into master as-is, and as such I'm slightly confused why this pull request even exists :)

**Comment by manuel-rubio** [comment]
ok, sorry @paweljw , closing the PR.

**Comment by jbernardo95** [comment]
I see. Makes sense to me !

I opened an issue for this (#17).

@manuel-rubio If you want to open a pr for this you are more than welcome. I will try to fix the 30 seconds issue and the migration to elixir 1.6 in the following days.

**Pull request closed without merging**
